#!/bin/bash
for folderName in /home/arroyo/Projectes/Projectes-Intellij/StrategyGame/assets/Images/characters/*; do
  for file in $folderName/*.png;do
    name=${file##*/}
    folder=${folderName##*/}
    baseName=${name%.png}
    path="/home/arroyo/Projectes/Projectes-Intellij/StrategyGame/assets/Images/characters/$folder/"
    height=$(identify -format "%h" $path$name)
    width=$(identify -format "%w" $path$name)
    nwidth=$((width / 2))
    nheight=$((height / 2))
    kk="x"
    addon="_small.png"
    #echo "$width $height $nwidth $nheight"
    convert $path$name -resize $nwidth$kk$nheight $path$baseName$addon

  done
done
